### PR TITLE
fix: detect and clean up zombie worktree loops (#202)

### LINKED ISSUE #202: Bug: Worktree loop becomes zombie when worktree directory is removed but registry entry persists
## Summary

When a parallel loop's worktree directory is removed (by external process, git operation, or cleanup), the loop registry (`loops.json`) retains the entry and the ralph process continues running. This creates a "zombie loop" that appears as `running` in `ralph loops list` but cannot perform any work, blocking the parallel slot and confusing users into thinking parallel execution is active.

## Environment

- **ralph version**: latest (compiled from source, Rust binary)
- **OS**: macOS (Darwin 24.3.0, arm64)
- **Git version**: 2.x

## Steps to Reproduce

1. Start a primary loop: `ralph run -b codex -p "Task A"`
2. Start a second loop (auto-spawns to worktree): `ralph run -b claude -p "Task B"`
3. Observe worktree created at `.worktrees/<loop-id>/`
4. The worktree directory gets removed (e.g., by another process, manual cleanup, or git worktree prune)
5. Run `ralph loops list`

## Expected Behavior

- Ralph should detect that the worktree directory no longer exists
- The loop should be marked as `orphan` or automatically cleaned up
- `ralph loops list` should show accurate status

## Actual Behavior

- `ralph loops list` shows the loop as `running`
- The ralph process (PID visible in `loops.json`) is still alive but operating on a non-existent directory
- `ralph loops stop <id>` fails with "Cannot determine active loop - it may have already stopped"
- The only way to clean up is manual `kill <pid>` + editing `loops.json`

## Observed State

```
$ ralph loops list
Loops: running: 2

ID                   STATUS       MERGE    AGE      LOCATION             PROMPT
----------------------------------------------------------------------------------------
(primary)            running      -        -        (in-place)           Task A...
true-brook           running      -        -        true-brook           Task B...

$ ls -la .worktrees/true-brook
# Directory is empty (only . and ..)

$ git worktree list
/path/to/repo      56639be [fix/app-registry-review-fixes]
# No true-brook worktree listed
```

## Root Cause Analysis

Three areas in the codebase lack worktree existence validation:

### 1. `loop_registry.rs` — `LoopEntry::is_alive()` (line ~129)

Currently only checks if the PID is alive via `kill(pid, 0)`. Does not verify the worktree directory exists.

```rust
#[cfg(unix)]
pub fn is_alive(&self) -> bool {
    use nix::sys::signal::kill;
    use nix::unistd::Pid;
    kill(Pid::from_raw(self.pid as i32), None)
        .map(|_| true)
        .unwrap_or(false)
}
```

**Suggested fix**: Add worktree path existence check for entries that have `worktree_path`:

```rust
pub fn is_alive(&self) -> bool {
    let pid_alive = /* existing PID check */;
    if !pid_alive {
        return false;
    }
    // For worktree loops, also verify the directory exists
    if let Some(ref wt_path) = self.worktree_path {
        return std::path::Path::new(wt_path).exists();
    }
    true
}
```

### 2. `loop_runner.rs` — No runtime worktree health check

The event loop in `run_loop_impl` does not verify the workspace directory exists between iterations. If the worktree is removed mid-execution, the loop continues running but all file operations silently fail or error.

**Suggested fix**: Add a workspace existence check at the start of each iteration:

```rust
// At the beginning of each iteration
if !loop_context.workspace().exists() {
    error!("Workspace directory no longer exists: {}", loop_context.workspace().display());
    // Deregister from registry and exit gracefully
    break TerminationReason::WorkspaceGone;
}
```

### 3. `loops.rs` — `list` command doesn't detect orphans

The `list` subcommand displays status based solely on PID liveness. It should cross-reference with actual worktree existence and show `orphan` status when the directory is missing.

### 4. `loops.rs` — `stop` command fails on zombie loops

`ralph loops stop <id>` fails because it can't determine the active loop context. It should still be able to kill the PID and clean up the registry entry even when the worktree is gone.

## Suggested Priority

**Medium-High** — This silently breaks parallel execution, which is a core v2 feature. Users see "2 loops running" but only 1 is actually working, with no indication of the problem.

## Workaround

Manual cleanup:
```bash
kill <zombie_pid>
# Edit .ralph/loops.json to remove the stale entry
# Or: ralph loops prune (if the PID is already dead)
```

### PR DESCRIPTION
**Pull request by CoderMageFox**
## Problem

When a parallel loop's worktree directory is removed externally, the loop process keeps running and the registry entry persists as `running`. This creates zombie loops that block parallel slots and can't be stopped via `ralph loops stop`. The only workaround is manual `kill` + editing `loops.json`.

## Solution

Adds zombie detection at multiple layers so they are automatically cleaned up:

- **`is_alive()`** now checks worktree directory existence in addition to PID — this is the highest-leverage fix since `with_lock()`, `clean_stale()`, and `list()` all call it
- **`is_pid_alive()`** added for raw PID checks when you need to send signals to orphan processes
- **`WorkspaceGone`** termination reason so running loops self-exit when their workspace disappears
- **`ralph loops list`** shows `orphan` status when PID alive but worktree gone
- **`ralph loops stop`** falls back to registry PID + signal when worktree is missing
- **`ralph loops discard`** gracefully handles already-removed worktrees (no more `NotFound` errors)

## Files Changed

| File | Change |
|------|--------|
| `crates/ralph-core/src/loop_registry.rs` | `is_alive()` worktree check + `is_pid_alive()` + 2 new tests |
| `crates/ralph-core/src/event_loop/mod.rs` | `WorkspaceGone` variant + workspace check in `check_termination()` |
| `crates/ralph-core/src/summary_writer.rs` | `status_text()` match arm |
| `crates/ralph-cli/src/loops.rs` | `list`, `stop`, `discard` fixes |
| `crates/ralph-cli/src/display.rs` | `WorkspaceGone` display match arm |
| `crates/ralph-cli/src/loop_runner.rs` | `WorkspaceGone` in history + merge queue match arms |
| `crates/ralph-bench/src/main.rs` | `WorkspaceGone` in bench format match arm |

## Testing

- 684 ralph-core lib tests pass
- 245 ralph-cli tests pass (including updated existing test for worktree path handling)
- 2 new tests: `test_zombie_worktree_detected_as_dead`, `test_no_worktree_entry_unaffected`

Closes #202

### CODE REVIEW

**Comment by CoderMageFox** [comment]
## CI Note

The Clippy and Test failures are **not caused by this PR**. They are pre-existing on `main` — the latest commit `504fa82` (feat: add kiro-acp backend) introduced missing fields (`cache_read_tokens`, `cache_write_tokens`, `input_tokens`, etc.) in `SessionResult` and `PtyExecutionResult` structs in `ralph-adapters`.

Verified locally:
```
git checkout origin/main
cargo build
# → same E0063 errors
```

This PR only touches `ralph-core` and `ralph-cli` — no changes to `ralph-adapters`.

**Comment by CoderMageFox** [comment]
## CI Fix Summary

Commit `26bb147` addresses the CI blockers that were failing this PR:

1. Fix `E0063` in `ralph-adapters` (struct initializers not updated after new fields)
- `crates/ralph-adapters/src/acp_executor.rs`
- Added the new token/cost fields to `SessionResult` / `PtyExecutionResult` initializers (ACP currently reports `0` for these).

2. Fix `E0063` in `ralph-cli`
- `crates/ralph-cli/src/loop_runner.rs`
- Updated `ExecutionOutcome` initialization to include the new fields.

3. Fix toolchain compatibility in smoke tests
- `crates/ralph-core/tests/smoke_runner.rs`
- Replaced `Duration::from_mins(1)` with `Duration::from_secs(60)` to avoid unstable API usage.

4. Stabilize color-related tests under environment variance
- `crates/ralph-cli/src/main.rs`
- `crates/ralph-cli/tests/integration_clean.rs`
- Aligned tests with `NO_COLOR` semantics (`--color always` test now explicitly removes `NO_COLOR`).

Local verification:
- `cargo test` ✅
- `cargo clippy --all-targets --all-features -- -D warnings` ✅
- `cargo test -p ralph-core smoke_runner` ✅

CI has been retriggered and is now running on the updated commit.

**Comment by CoderMageFox** [comment]
Addressed the remaining CI failure in `web::tests::check_npm_reads_version`.

What was happening:
- The test uses a freshly written fake executable, and CI occasionally hits transient spawn errors (`text file busy` / `ETXTBSY`).
- Those transient errors were being mapped to the generic "npm is not installed" message.

What I changed:
- Added a small retry wrapper for command execution in `crates/ralph-cli/src/web.rs`.
- Routed both `check_node_with` and `check_npm_with` through that retry path.
- Retries are short and only continue on transient exec errors.

Validation:
- `cargo test` passes locally.
- `cargo test -p ralph-core smoke_runner` passes locally.

Commit: `5574715`

**Comment by CoderMageFox** [comment]
Follow-up fix for the latest CI failure (`Test` job):

- Failure: `pty_executor::tests::test_run_observe_streaming_text_routes_output` intermittently captured only `alpha` and missed trailing output.
- Root cause: race between child exit detection and the PTY reader thread flushing final bytes into the channel.
- Fix: added a short post-exit drain window (200ms) in both observe paths:
  - `run_observe`
  - `run_observe_streaming`

This ensures trailing PTY output is consumed before returning.

Validation run locally:
- `cargo test`
- `cargo test -p ralph-core smoke_runner`
- stress loop of the flaky test (120 runs) all passed

Commit: `0a77a9f`

**Comment by mikeyobrien** [comment]
Appreciate cleaning up some of the CI mess.

File: crates/ralph-cli/src/loops.rs [hunk 1]
```diff
@@ -692,6 +699,50 @@ fn stop_loop(args: StopArgs) -> Result<()> {
...
+                    );
+                    kill(Pid::from_raw(entry.pid as i32), signal)
+                        .context("Failed to send signal to orphan loop")?;
+                }
+                #[cfg(not(unix))]
+                {
+                    bail!("Signal sending not supported on this platform");
+                }
+            }
+            let _ = registry.deregister(&loop_id);
```
Comment (mikeyobrien) [inline crates/ralph-cli/src/loops.rs:793]: Blocking: this unconditionally deregisters right after sending a signal. If SIGTERM is ignored (or process hasn’t exited yet), `ralph loops stop` reports success and removes discoverability while the orphan process is still running. I reproduced this with a TERM-ignoring process: stop prints cleaned up, process remains alive, and `loops list` is empty. Please only deregister after confirming exit (or keep the entry as orphan if still alive).

File: crates/ralph-cli/src/loops.rs [hunk 2]
```diff
@@ -669,8 +672,12 @@ fn discard_loop(args: DiscardArgs) -> Result<()> {
 
     // Remove worktree if exists
     if let Some(wt_path) = worktree_path {
-        println!("Removing worktree at {}...", wt_path);
-        remove_worktree(&cwd, &wt_path)?;
+        if PathBuf::from(&wt_path).is_dir() {
+            println!("Removing worktree at {}...", wt_path);
+            remove_worktree(&cwd, &wt_path)?;
+        } else {
+            println!("Worktree already removed: {}", wt_path);
```
Comment (mikeyobrien) [inline crates/ralph-cli/src/loops.rs:680]: Blocking: when the directory is already missing, this path skips `remove_worktree()`, which also handles `git worktree remove`, `git worktree prune`, and `ralph/<loop-id>` branch cleanup. In practice `discard` reports success but stale worktree metadata/branch remain, and the loop can still appear as orphan in `loops list`. Please run a fallback cleanup path (at least prune + branch delete) even when `wt_path` is gone.

**Comment by CoderMageFox** [comment]
Addressed the blocking feedback on `discard` when the worktree directory is already missing.

### What changed
- `crates/ralph-cli/src/loops.rs`
- In the `Worktree already removed` branch, `discard` now runs fallback cleanup via `cleanup_missing_worktree_artifacts(...)`:
  - `git worktree prune`
  - `git branch -D ralph/<loop-id>`
- This preserves cleanup behavior even when `remove_worktree()` cannot run because `wt_path` is gone.

### Verification
- Added unit test: `test_discard_loop_missing_worktree_runs_fallback_cleanup`
  - Creates a repo + `ralph/<loop-id>` branch
  - Registers loop with missing worktree path
  - Confirms `discard` removes branch, marks queue entry `discarded`, and deregisters loop
- Also re-ran existing discard test:
  - `test_discard_loop_marks_discarded_and_deregisters`

Commit: `882ea78`

**Comment by CoderMageFox** [comment]
Addressed the second blocking review on `loops stop` orphan cleanup semantics.

### What changed
- `crates/ralph-cli/src/loops.rs`
- In the `worktree_gone` + registry fallback path, `stop` now:
  1. sends SIGTERM/SIGKILL
  2. waits briefly for actual process exit
  3. only deregisters when exit is confirmed
- If the process is still alive after the signal, command now errors and keeps the registry entry discoverable as orphan.

### Why
Previously we deregistered unconditionally right after sending signal, so `stop` could report success while the process remained alive (hidden from `loops list`).

### Verification
- Added unit test: `test_stop_loop_orphan_keeps_registry_when_term_ignored`
  - Spawns a TERM-ignoring process
  - Calls `stop` on orphan loop
  - Verifies command fails with "still running" and registry entry remains

Commit: `684493f`

**Comment by CoderMageFox** [comment]
Follow-up patch for the audit findings is now pushed.

### Additional hardening added

1) `discard` fallback cleanup now also runs when `worktree_path` is `None`
- `crates/ralph-cli/src/loops.rs`
- Previously, fallback cleanup (`git worktree prune` + branch delete) only ran when a stored path existed but directory was missing.
- Now we also run fallback cleanup when no worktree path is present (e.g., queue-resolved loop with stale `ralph/<loop-id>` branch).

2) orphan `stop` wait is no longer fixed to a hardcoded 2s
- `crates/ralph-cli/src/loops.rs`
- Added `orphan_stop_wait_timeout(force)`:
  - default: 5s for SIGTERM path
  - default: 2s for SIGKILL path
  - override via `RALPH_LOOPS_STOP_WAIT_MS`
- Error message now includes actual wait duration in ms.

### Added/updated verification
- `test_discard_loop_without_worktree_path_runs_fallback_cleanup`
- Re-ran:
  - `test_discard_loop_missing_worktree_runs_fallback_cleanup`
  - `test_stop_loop_orphan_keeps_registry_when_term_ignored`

Commit: `c9fcf6f`
